version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    env_file:
      - .env
    ports:
      - '8001:3000'

  courses:
    build:
      context: .
      dockerfile: Dockerfile-courses
    env_file:
      - .env
    ports:
      - '8002:3000'

  quizzes:
    build:
      context: .
      dockerfile: Dockerfile-quizzes
    env_file:
      - .env
    ports:
      - '8003:3000'

  users:
    build:
      context: .
      dockerfile: Dockerfile-users
    env_file:
      - .env
    ports:
      - '8004:3000'
