services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile-auth
    environment:
      - DB_URL=${DB_URL}
      - SENTRY_DSN=${SENTRY_DSN_AUTH}
      - SENTRY_ORG=${SENTRY_ORG}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    env_file:
      - .env
    ports:
      - '8001:3000'

  courses:
    build:
      context: .
      dockerfile: Dockerfile-courses
    environment:
      - DB_URL=${DB_URL}
      - SENTRY_DSN=${SENTRY_DSN_COURSES}
      - SENTRY_ORG=${SENTRY_ORG}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    env_file:
      - .env
    ports:
      - '8002:3000'

  quizzes:
    build:
      context: .
      dockerfile: Dockerfile-quizzes
    environment:
      - DB_URL=${DB_URL}
      - SENTRY_DSN=${SENTRY_DSN_QUIZZES}
      - SENTRY_ORG=${SENTRY_ORG}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    env_file:
      - .env
    ports:
      - '8003:3000'

  users:
    build:
      context: .
      dockerfile: Dockerfile-users
    environment:
      - DB_URL=${DB_URL}
      - SENTRY_DSN=${SENTRY_DSN_USERS}
      - SENTRY_ORG=${SENTRY_ORG}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
    env_file:
      - .env
    ports:
      - '8004:3000'
